spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq.socshared.ml} # RabbitMQ host.
    password: ${RABBIT_PASS:admin} # Login to authenticate against the broker.
    port: ${RABBIT_PORT:5672} # RabbitMQ port.
    username: ${RABBIT_USER:admin} # Login user to authenticate to the broker.

management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, health, httptrace, info, loggers, metrics, mappings, shutdown

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}
    storage: ${STORAGE_SERVICE:https://storage.socshared.ml}
    fb: ${FB_SERVICE:https://fb.socshared.ml}
    vk: ${VK_SERVICE:https://vk.socshared.ml}
    bstat: ${BSTAT_SERVICE:https://bstat.socshared.ml}